# Generated by Django 5.1.5 on 2025-03-01 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
        migrations.CreateModel(
            name='MembershipTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.membership')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='tags',
            field=models.ManyToManyField(blank=True, through='app.MembershipTag', to='app.tag'),
        ),
    ]
