# Generated by Django 5.1.5 on 2025-03-01 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_userprofile_tags_membershiptag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptag',
            name='tag',
            field=models.ForeignKey(default=list, on_delete=django.db.models.deletion.CASCADE, to='app.tag'),
        ),
    ]
