# Generated by Django 5.1.5 on 2025-01-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_lead_email_alter_lead_organization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='tags',
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
