# Generated by Django 5.1.5 on 2025-03-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_membershiptag_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='tags',
        ),
        migrations.AddField(
            model_name='membership',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
