# Generated by Django 5.1.5 on 2025-03-01 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_membership_tags_membership_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='tags',
        ),
        migrations.AlterField(
            model_name='membershiptag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tag'),
        ),
        migrations.AddField(
            model_name='membership',
            name='tags',
            field=models.ManyToManyField(blank=True, through='app.MembershipTag', to='app.tag'),
        ),
    ]
