# Generated by Django 5.1.5 on 2025-02-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_leadassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.JSONField(default=list),
        ),
    ]
