# Generated by Django 5.1.5 on 2025-02-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
