# Generated by Django 5.1.5 on 2025-02-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_first_name_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
    ]
