# Generated by Django 5.1.5 on 2025-02-06 08:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_leadassignment_expires_at_leadassignment_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadhistory',
            name='action',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadhistory',
            name='timestamp',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
