# Generated by Django 5.1.5 on 2025-02-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_leadhistory_action_leadhistory_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadhistory',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='leadhistory',
            name='user_response_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
