# Generated by Django 5.1.5 on 2025-02-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_leadhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadassignment',
            name='token',
        ),
    ]
