# Generated by Django 5.1.5 on 2025-02-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_membership_invite_status_userprofile_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
    ]
