# Generated by Django 5.1.5 on 2025-02-23 17:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_membership_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='isUser',
            new_name='is_user',
        ),
        migrations.AddField(
            model_name='membership',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
