# Generated by Django 5.1.5 on 2025-02-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_rename_isuser_membership_is_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='LeadsOwned',
            field=models.ManyToManyField(blank=True, null=True, to='app.lead'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
