# Generated by Django 5.1.5 on 2025-02-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_userprofile_leadsowned_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='invite_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
